name: Integration Test

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Clone Integration Test
        run: |
          git clone https://$(GIT_TOKEN)@github.com/cto-ai/sdk-integration-testing.git
          cd sdk-integration-testing
          docker build --pull -t js-test:latest -f Dockerfile.javascript . && docker run --rm js-test:latest
