name: Integration Test

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Clone integration test
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
