name: Integration Test

on:
  workflow_dispatch:
  
env: 
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Clone Integration Test
        run: |
          git clone https://${{ env.GIT_TOKEN }}@github.com/cto-ai/sdk-integration-testing.git
          cd sdk-integration-testing
          docker build --pull -t js-test:latest -f Dockerfile.javascript . && docker run --rm js-test:latest
