name: Test Tag

on:

  workflow_dispatch:
    inputs:
        tagToTest:
          description: 'Tag to test'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tagToTest }}
      - uses: actions/setup-node@v1
        name: Use version ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
